name: CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: descargar repositorio
        uses: actions/checkout@v3
      - name: pruebas-unitarias
        run: mvn test
      - name: compilar la aplicación sin repetir pruebas
        run: mvn package -DskipTests=true

  test:
    needs: build
    runs-on: self-hosted
    steps:
      - name: descargar repositorio
        uses: actions/checkout@v3
      - name: instalar aplicación en Tomcat
        run: |
          mvn package -DskipTests=true
          cp -r target/Baloncesto /usr/local/tomcat/webapps
      - name: preparar base de datos de prueba
        run: |
          mysql -u root < db/baloncesto.sql
          export DATABASE_HOST="jdbc:mysql://localhost"
          export DATABASE_PORT="3306"
          export DATABASE_NAME="baloncesto"
          export DATABASE_USER="usuario"
          export DATABASE_PASS="clave"
          sh /usr/local/tomcat/bin/catalina.sh stop
          sh /usr/local/tomcat/bin/catalina.sh start
      - name: realizar pruebas funcionales
        run: |
          mvn failsafe:integration-test failsafe:verify

  qa:
    needs: test
    runs-on: self-hosted
    continue-on-error: true
    steps:
      - name: calidad-codigo
        run: |
          mvn sonar:sonar -Dsonar.host.url=http://sonarqube:9000 -Dsonar.qualitygate.wait=true -Dsonar.login=admin -Dsonar.password=admin
  testing:
    runs-on: ubuntu-latest
    needs: qa
    if: github.ref == 'refs/heads/dev'
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3
      - name: Crear el archivo .war
        run: |
          mvn package -DskipTests=true
      - name: Desplegar Testing en Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: baloncesto-testing
          publish-profile: ${{ secrets.AZURE_TESTING }}
          package: target/*.war
  stage:
    runs-on: ubuntu-latest
    needs: qa
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3
      - name: Crear el archivo .war
        run: |
          mvn package -DskipTests=true
      - name: Desplegar Pre en Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: baloncesto-pre
          publish-profile: ${{ secrets.AZURE_PRE }}
          package: target/*.war
  deploy:
    runs-on: ubuntu-latest
    needs: [qa,stage]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Descargar repositorio
        uses: actions/checkout@v3
      - name: Crear el archivo .war
        run: |
          mvn package -DskipTests=true
      - name: Aprobación manual para despliegue en producción
        uses: trstringer/manual-approval@v1
        with:
         secret: ${{ github.TOKEN }}
         approvers: cruzmediaorg
         issue-title: "Aprobación para despliegue en producción"
         issue-body: "Por favor, aprueba este despliegue para producción"
         additional-approved-words: "UAHReady"
         additional-denied-words: "UAHNotReady"
      - name: Desplegar en Azure
        uses: Azure/webapps-deploy@v2
        with:
          app-name: baloncesto-uah
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: target/*.war
